[build]
  command   = "npm install && npm run build:all"
  functions = "functions/"
  publish   = "build"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
  
[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/server/:splat"
  status = 200


  # [functions]
  #   included_files = [ "database/**" ]
